apiVersion: apps/v1
kind: Deployment
metadata:
  name: 01deploy
  labels:
    app: httpd
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: httpd
          image: naveenthangella/deploy:v1

---
kind: Service
apiVersion: v1
metadata:
  name: deploy-service
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
