---
kind: Namespace
apiVersion: v1
metadata:
  name: web

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web-deploy
  namespace: web
  labels:
    app: nginx
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: web

  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
        - name: nginx
          image: naveenthangella/snginx:v1
          env:
            - name: TOMCAT_IP
              value: tomcat-svc.app.svc.cluster.local
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: web-svc
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80