---
kind: Pod
apiVersion: v1
metadata:
  name: 05-secret
spec:
  containers:
    - name: centos
      image: centos
      env:
        - name: PROJECT
          valueFrom:
            secretKeyRef:
              key: PROJECT
              name: secret1
      command:
        - "sleep"
        - "1000"

---

kind: Secret
apiVersion: v1
metadata:
  name: secret1
type: Opaque
data:
  PROJECT:  REVWT1BT