kind: Pod
apiVersion: v1
metadata:
  name: 06-resources
spec:
  containers:
    - name: centos
      image: centos:7
      resources:
        requests:
          cpu:  "150m"
          memory: "256Mi"
        limits:
          cpu:  "200m"
          memory: "400Mi"
      command:
        - "sleep"
        - "1000"