---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-claim
spec:
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

kind: Pod
apiVersion: v1
metadata:
  name: 07-pvc
spec:
  volumes:
    - name: sample-claim
      persistentVolumeClaim:
        claimName: sample-claim
  containers:
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "1000"
      volumeMounts:
        - mountPath: /opt
          name: sample-claim